name: auto-merge

on:
  pull_request_targetï¼š

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'|| github.actor == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
            github-token: ${{ secrets.MY_TOKEN }} 
